# from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier
from model.keypoint_classifier.keypoint_classifier1 import KeyPointClassifier1
# from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.point_history_classifier.point_history_classifier1 import PointHistoryClassifier1
from model.point_history_classifier.point_history_classifier_fullhand1 import PointHistoryClassifierFullhand1

